---
- name: Setup Docker Repository
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - gnupg
          - curl
        state: present
        update_cache: yes

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /tmp/docker.gpg

    - name: Convert Docker GPG key to dearmor format
      command: gpg --dearmor -o /etc/apt/trusted.gpg.d/debian.gpg /tmp/docker.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/debian.gpg

    - name: Add Docker repository to Apt sources
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/trusted.gpg.d/debian.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
