---
- name: Setup Kubernetes Master Node
  hosts: all
  become: yes
  tasks:
    - name: Update package list and install prerequisites
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      # This task updates the package list and installs essential packages.

    - name: Configure sysctl settings for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
      notify: Reload sysctl
      # This task creates a sysctl configuration file with settings required for Kubernetes networking.

    - name: Load overlay kernel module
      command: modprobe overlay
      # This task loads the overlay kernel module necessary for Kubernetes networking.

    - name: Load br_netfilter kernel module
      command: modprobe br_netfilter
      # This task loads the br_netfilter kernel module necessary for Kubernetes networking.

    - name: Add Docker's GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/debian.gpg
      args:
        warn: false
      # This task adds Docker's GPG key to verify Docker packages.

    - name: Add Docker repository to Apt sources
      command: sudo add-apt-repository "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
      # This task adds Docker's APT repository to the system.

    - name: Update package list and install containerd
      apt:
        update_cache: yes
        name: containerd.io
        state: present
      # This task updates the package list and installs containerd.

    - name: Generate containerd default configuration
      shell: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
      # This task generates the default containerd configuration file.

    - name: Enable Systemd Cgroup in containerd configuration
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^SystemdCgroup = false'
        line: 'SystemdCgroup = true'
        state: present
      # This task updates the containerd configuration to enable Systemd Cgroup.

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
        enabled: yes
      # This task restarts the containerd service to apply the new configuration.

  handlers:
    - name: Reload sysctl
      command: sysctl --system
      # This handler reloads sysctl settings a
