---
- name: Setup Docker on Debian
  hosts: all
  become: yes
  vars:
    debian_codename: bookworm  # Manually set the Debian codename

  tasks:
    - name: Update package list and install prerequisites
      apt:
        update_cache: yes
        name:
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      # This task updates the package list and installs essential packages.

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /tmp/docker.gpg
      # This task downloads Docker's GPG key.

    - name: Add Docker's GPG key
      command: gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg /tmp/docker.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/docker.gpg
      # This task converts Docker's GPG key to a format suitable for APT.

    - name: Add Docker repository to Apt sources
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian {{ debian_codename }} stable
      # This task adds Docker's APT repository for Debian.

    - name: Update apt cache
      apt:
        update_cache: yes
      # This task updates the package list to include Docker's repository.

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present
      # This task installs containerd.

    - name: Verify containerd installation
      command: containerd --version
      register: containerd_version
      ignore_errors: yes

    - name: Display containerd version
      debug:
        msg: "containerd version: {{ containerd_version.stdout }}"
      # This task displays the installed containerd version.

    - name: Configure sysctl for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
      # This task writes kernel parameters for Kubernetes to a sysctl configuration file.

    - name: Apply sysctl configuration
      command: sysctl --system
      # This task applies the new sysctl settings.

    - name: Load overlay kernel module
      command: modprobe overlay
      # This task loads the overlay kernel module.

    - name: Load br_netfilter kernel module
      command: modprobe br_netfilter
      # This task loads the br_netfilter kernel module.

    - name: Configure containerd to use systemd cgroup
      block:
        - name: Ensure default containerd config file exists
          command: containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
          # This task creates the default containerd config file if it does not exist.

        - name: Update containerd config to use systemd cgroup
          command: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
          # This task updates the containerd config to enable systemd cgroup.

        - name: Restart and enable containerd service
          systemd:
            name: containerd
            state: restarted
            enabled: yes
          # This task restarts and enables the containerd service.
