---
- name: Setup Kubernetes Master Node
  hosts: all
  become: yes
  tasks:
    - name: Update package list and install prerequisites
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Add Docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository to Apt sources
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker
      # This task adds Docker's repository to the system.

    - name: Update package list after adding Docker repository
      apt:
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd.io
        state: present

    - name: Generate containerd default configuration
      shell: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1

    - name: Enable Systemd Cgroup in containerd configuration
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^SystemdCgroup = false'
        line: 'SystemdCgroup = true'
        state: present

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
        enabled: yes

  handlers:
    - name: Reload sysctl
      command: sysctl --system
