---
- name: Setup Docker on Debian
  hosts: all
  become: yes
  tasks:
    - name: Update package list and install prerequisites
      apt:
        update_cache: yes
        name:
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      # This task updates the package list and installs essential packages.

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /tmp/docker.gpg
      # This task downloads Docker's GPG key.

    - name: Add Docker's GPG key
      command: gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg /tmp/docker.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/docker.gpg
      # This task converts Docker's GPG key to a format suitable for APT.

    - name: Add Docker repository to Apt sources
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable
      # This task adds Docker's APT repository for Debian.

    - name: Update apt cache
      apt:
        update_cache: yes
      # This task updates the package list to include Docker's repository.

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present
      # This task installs containerd.

    - name: Verify containerd installation
      command: containerd --version
      register: containerd_version
      ignore_errors: yes

    - name: Display containerd version
      debug:
        msg: "containerd version: {{ containerd_version.stdout }}"
      # This task displays the installed containerd version.
