---
- name: Setup Docker Repository
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present
        update_cache: yes

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      command: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.gpg

    - name: Convert Docker's GPG key to dearmor format
      command: gpg --dearmor -o /etc/apt/keyrings/docker-archive-keyring.gpg /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository to Apt sources
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd.io
        state: present
        update_cache: yes
