- name: Setup Kubernetes Worker Node
  hosts: worker
  become: yes
  tasks:
    - name: Update package list and install prerequisites
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      # Updates the package list and installs essential packages.

    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/kubernetes.gpg
      # Downloads Kubernetes' GPG key.

    - name: Add Kubernetes' GPG key
      command: gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes.gpg /tmp/kubernetes.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/kubernetes.gpg
      # Adds Kubernetes' GPG key to the trusted APT keyring.

    - name: Add Kubernetes repository to Apt sources
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /
      # Adds the Kubernetes repository to the Apt sources list.

    - name: Update package list again to include Kubernetes repository
      apt:
        update_cache: yes
      # Updates the package list to include the new Kubernetes repository.

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
      # Installs the Kubernetes components kubelet, kubeadm, and kubectl.

    - name: Mark Kubernetes packages as held to prevent accidental upgrades
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
      # Holds the Kubernetes packages to prevent them from being upgraded accidentally.

    - name: Verify installations
      command: >
        kubectl version --client && echo && kubeadm version
      register: kube_versions
      ignore_errors: yes
      # Verifies the installations of Kubernetes components by checking their versions.

    - name: Disable swap to meet Kubernetes requirements
      command: swapoff -a
      # Disables swap to meet Kubernetes requirements.

    - name: Comment out swap entry in fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        line: '# &'
        state: present
      # Comments out the swap entry in fstab to ensure swap is not enabled on reboot.

    - name: Install UFW
      apt:
        name: ufw
        state: present
      # Installs UFW (Uncomplicated Firewall).

    - name: Enable UFW
      ufw:
        state: enabled
      # Enables UFW.

    - name: Allow necessary ports for Kubernetes worker node communication
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: tcp
        comment: "{{ item.name }}"
      loop:
        - { name: 'Kubelet API', port: 10250 }
        - { name: 'NodePort Services', port: '30000:32767' }
      # Allows necessary ports for Kubernetes worker node communication through UFW.

    - name: Reload UFW to apply changes
      command: ufw reload
      # Reloads UFW to apply the new rules.

    - name: Display setup completion message
      debug:
        msg: "Kubernetes worker node setup is complete."
      # Displays a message indicating the completion of the setup.
