---
- name: Setup Kubernetes Master Node
  hosts: masternode_servers
  become: yes
  tasks:
    - name: Update package list and install prerequisites
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      # Updates the package list and installs essential packages.

    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/kubernetes.gpg
      # Downloads Kubernetes' GPG key.

    - name: Add Kubernetes' GPG key
      command: gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes.gpg /tmp/kubernetes.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/kubernetes.gpg
      # Adds Kubernetes' GPG key to the trusted APT keyring.

    - name: Add Kubernetes repository to Apt sources
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /
      # Adds the Kubernetes repository to the Apt sources list.

    - name: Update package list again to include Kubernetes repository
      apt:
        update_cache: yes
      # Updates the package list to include the new Kubernetes repository.

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
      # Installs the Kubernetes components kubelet, kubeadm, and kubectl.

    - name: Mark Kubernetes packages as held to prevent accidental upgrades
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
      # Holds the Kubernetes packages to prevent them from being upgraded accidentally.

    - name: Verify Kubernetes installations
      command: >
        kubectl version --client && echo && kubeadm version
      register: kube_versions
      ignore_errors: yes
      # Verifies the installations of Kubernetes components by checking their versions.

    - name: Disable swap
      command: swapoff -a
      # Disables swap to meet Kubernetes requirements.

    - name: Comment out swap entry in fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        line: '# &'
        state: present
      # Comments out the swap entry in fstab to ensure swap is not enabled on reboot.

    - name: Install UFW
      apt:
        name: ufw
        state: present
      # Installs UFW (Uncomplicated Firewall).

    - name: Enable UFW
      ufw:
        state: enabled
      # Enables UFW.

    - name: Allow necessary ports for Kubernetes and SSH
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: tcp
        comment: "{{ item.name }}"
      loop:
        - { name: 'Kubernetes API server', port: 6443 }
        - { name: 'etcd server client API', port: 2379 }
        - { name: 'etcd server peer API', port: 2380 }
        - { name: 'Kubelet API', port: 10250 }
        - { name: 'Kube-scheduler', port: 10251 }
        - { name: 'Kube-controller-manager', port: 10252 }
        - { name: 'Kubelet read-only port', port: 10255 }
        - { name: 'SSH', port: 22 }
      # Allows necessary ports for Kubernetes and SSH access through UFW.

    - name: Reload UFW to apply changes
      command: ufw reload
      # Reloads UFW to apply the new rules.

    - name: Initialize Kubernetes cluster
      command: kubeadm init
      register: kubeadm_init
      # Initializes the Kubernetes cluster and registers the output.

    - name: Display Kubernetes cluster initialization status
      debug:
        msg: "Kubernetes master node setup complete. Use the following command on worker nodes to join the cluster: {{ kubeadm_init.stdout_lines[0] }}"
      # Displays a message indicating the setup is complete and provides the join command for worker nodes.

    - name: Set up kubeconfig for the current user
      become: no
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      # Configures kubectl for the current user.

    - name: Download Calico manifest
      get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
        dest: /tmp/calico.yaml
      # Downloads the Calico manifest.

    - name: Apply Calico manifest
      command: kubectl apply -f /tmp/calico.yaml
      # Applies the Calico manifest to configure networking.

    - name: Display setup completion message
      debug:
        msg: "Kubernetes master node setup complete."
      # Displays a message indicating the setup is complete.
